# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blueprint3D
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Blueprint3D is an open source web-based home and interior design platform. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

github_username:  furnishup

# Build settings
markdown: kramdown
